/**
 * DynamicBot — Qualtrics Chat Widget JS
 * =======================================
 * DO NOT EDIT THIS FILE DIRECTLY for deployment.
 * Use the Admin Panel (/admin) to generate a pre-filled version with your
 * BACKEND_URL and STUDY_ID already set.
 *
 * For local testing: update BACKEND_URL and STUDY_ID below, then open
 * qualtrics_widget.html in a browser via file://.
 */

// ── Configuration (auto-filled by Admin Panel "Embed Code" tab) ──────────────
const BACKEND_URL = 'http://localhost:8000'; // CHANGE THIS to your deployed API URL
const STUDY_ID = 'REPLACE_WITH_STUDY_ID';   // Auto-filled by admin panel — do not modify
const MAX_TURNS = 3;
const DEV_CT = '37063020100'; // Census Tract used when testing via file:// in browser
// ─────────────────────────────────────────────────────────────────────────────

Qualtrics.SurveyEngine.addOnload(function () {
  // ── State ───────────────────────────────────────────────────────────────────
  let sessionId = null;
  let turnCount = 0;
  const transcript = []; // [{role: 'bot'|'user', text: string}]

  // ── DOM refs ─────────────────────────────────────────────────────────────────
  const messagesEl      = document.getElementById('chat-messages');
  const inputEl         = document.getElementById('user-input');
  const sendBtn         = document.getElementById('send-btn');
  const turnIndicatorEl = document.getElementById('turn-indicator');
  const typingEl        = document.getElementById('typing-indicator');
  const completionEl    = document.getElementById('completion-banner');
  const inputAreaEl     = document.getElementById('chat-input-area');

  // ── Determine Census Tract ────────────────────────────────────────────────
  const IS_DEV = window.location.protocol === 'file:';
  let censusTract;
  if (IS_DEV) {
    censusTract = DEV_CT;
  } else {
    censusTract =
      (Qualtrics.SurveyEngine.getEmbeddedData('CensusTract') || '').trim() ||
      'DEFAULT';
  }

  // ── Disable the Qualtrics Next button until the chat is complete ──────────
  const nextBtn = document.getElementById('NextButton');
  if (nextBtn) nextBtn.setAttribute('disabled', 'disabled');

  // ── Helper: append a message bubble ──────────────────────────────────────
  function appendMessage(role, text) {
    if (typingEl.parentNode === messagesEl) {
      messagesEl.removeChild(typingEl);
    }
    const bubble = document.createElement('div');
    bubble.className = 'message-bubble ' + (role === 'bot' ? 'bot-message' : 'user-message');
    bubble.textContent = text; // textContent (NOT innerHTML) — prevents XSS
    messagesEl.appendChild(bubble);
    messagesEl.appendChild(typingEl);
    messagesEl.scrollTop = messagesEl.scrollHeight;
    transcript.push({ role, text });
  }

  function appendError(text) {
    const el = document.createElement('div');
    el.className = 'error-message';
    el.textContent = text;
    messagesEl.insertBefore(el, typingEl);
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  function updateTurnIndicator() {
    turnIndicatorEl.textContent = 'Turn ' + turnCount + ' of ' + MAX_TURNS;
  }

  function setTyping(visible) {
    typingEl.classList.toggle('visible', visible);
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  function setLoading(isLoading) {
    inputEl.disabled = isLoading;
    sendBtn.disabled = isLoading;
    setTyping(isLoading);
  }

  function buildTranscriptString() {
    return transcript
      .map(e => '[' + e.role.toUpperCase() + ']: ' + e.text)
      .join('\n\n');
  }

  // ── Handle conversation completion ───────────────────────────────────────
  function handleConversationComplete() {
    inputAreaEl.style.display = 'none';
    completionEl.classList.add('visible');

    const transcriptString = buildTranscriptString();
    if (!IS_DEV) {
      Qualtrics.SurveyEngine.setEmbeddedData('ChatTranscript', transcriptString);
      Qualtrics.SurveyEngine.setEmbeddedData('ChatTurns', String(turnCount));
    } else {
      console.log('--- TRANSCRIPT ---\n' + transcriptString);
    }

    if (nextBtn) nextBtn.removeAttribute('disabled');
  }

  // ── Initialize: call /start ───────────────────────────────────────────────
  function initializeChat(ct) {
    setLoading(true);
    turnIndicatorEl.textContent = 'Loading...';

    fetch(BACKEND_URL + '/start', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ census_tract: ct, study_id: STUDY_ID }),
    })
      .then(res => {
        if (!res.ok) throw new Error('Server error ' + res.status);
        return res.json();
      })
      .then(data => {
        sessionId = data.session_id;
        turnCount = data.turn_count;
        updateTurnIndicator();
        appendMessage('bot', data.message);
        setLoading(false);
        inputEl.disabled = false;
        sendBtn.disabled = false;
        inputEl.focus();
      })
      .catch(err => {
        setLoading(false);
        turnIndicatorEl.textContent = 'Error';
        appendError(
          'The interview could not be loaded. Please refresh or contact the study team. (' + err.message + ')'
        );
        console.error('[DynamicBot] /start error:', err);
      });
  }

  // ── Send a user message: call /chat ──────────────────────────────────────
  function sendMessage() {
    const text = inputEl.value.trim();
    if (!text || !sessionId) return;

    setLoading(true);
    inputEl.value = '';
    appendMessage('user', text);

    fetch(BACKEND_URL + '/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: sessionId, user_message: text }),
    })
      .then(res => {
        if (!res.ok) {
          return res.json().then(body => { throw new Error(body.detail || 'Server error ' + res.status); });
        }
        return res.json();
      })
      .then(data => {
        turnCount = data.turn_count;
        updateTurnIndicator();
        appendMessage('bot', data.message);
        setLoading(false);

        if (data.conversation_complete) {
          handleConversationComplete();
        } else {
          inputEl.disabled = false;
          sendBtn.disabled = false;
          inputEl.focus();
        }
      })
      .catch(err => {
        setLoading(false);
        appendError('Something went wrong. Please try again. (' + err.message + ')');
        inputEl.disabled = false;
        sendBtn.disabled = false;
        console.error('[DynamicBot] /chat error:', err);
      });
  }

  // ── Event listeners ───────────────────────────────────────────────────────
  sendBtn.addEventListener('click', sendMessage);
  inputEl.addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); }
  });

  // ── Boot ──────────────────────────────────────────────────────────────────
  initializeChat(censusTract);
});
